export const products = [
  {
    id: "1",
    name: "Winter shoe",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    offPrice: 120,
    discount: 0,
    explain:"این کفش از کفی پیو و روکش چرمی تهیه شده تا در راحتی و خنکی تاثیر بسزایی داشته باشد. این کفش مخصوص استفاده شهری میباشد",
    size:37,
    image: "https://s4.uupload.ir/files/item1_soj.jpg",
  },
  {
    id: "2",
    name: "Adidas shoe",
    description: [{ support: "گارانتی مادام العمر" }, { support: "اورجینال" }],
    price: 110,
    explain:"این کفش مناسب استفاده ورزشی میباشد و با استفاده ازا ن کفش میتوانید نهایت راحتی را تجربه کنید",
    offPrice: 100,
    discount: 8,
    size:37,
    image: "https://s4.uupload.ir/files/item2_fc5s.jpg",
  },
  {
    id: "3",
    name: "Vans shoe",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    size:39,
    price: 99,
    explain:"این کفش مناسب استفاده برای مجالس و درون شهری میباشد و از ظاهری زیبا و راحتی فوق العاده برخوردار است",
    offPrice: 89,
    discount: 10,
    image: "https://s4.uupload.ir/files/item3_zvc9.jpg",
  },
  {
    id: "4",
    name: "Running shoe",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    size:39,
    price: 260,
    offPrice: 220,
    discount: 15,
    explain:"در طراحی این کفش از کفی پیو استفاده شده تا در فعالیت های ورزشی بتوانید راحتی کامل را تجربه کنید و همچنین با منافذ رویه کفش پای شما خنک میماند",
    image: "https://s4.uupload.ir/files/item4_zr94.jpg",
  },
  {
    id: "5",
    name: "Mountain shoe",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    size:40,
    price: 150,
    offPrice: 150,
    explain:"این کفش برای فصل زمستان و پاییز طراحی شده. همچنین از رویه چرمی برخوردار است که باعث ضد آب بودن کفش میشود",
    discount: 0,
    image: "https://s4.uupload.ir/files/item5_24ye.jpg",
  },
  {
    id: "6",
    name: "Jordan",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    explain:"این کفش از وزن سبکی برخوردار است که همین امر موجب راحتی شما در پیاده روی های طولانی میشود. ایم کفش مناسب استفاده شهری است",
    size:40,
    price: 220,
    offPrice: 200,
    discount: 13,
    image: "https://s4.uupload.ir/files/item6_7jfy.jpg",
  },
];

export const users = [
  {
    name: "Saheb mohamadi",
    email: "saheb.ex@gmail.com",
    password: "12345678",
    phoneNumber: "09180000000",
    isAdmin: true,
  },
  {
    name: "John",
    email: "user@example.com",
    password: "1234",
    isAdmin: false,
    phoneNumber: "09181230000",
  },
];
